name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build: #環境構築
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v2

      - name: pythonの環境構築
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: テスト実行
        run: |
          pytest --cov=math_operations --cov-report=term-missing
          