name: Test Python Code

on:
  push:
    branches:
      - main  # mainブランチにプッシュされた時に実行
  pull_request:
    branches:
      - main  # mainブランチにプルリクエストが作成された時に実行

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install httpx

      - name: Run tests
        run: |
          # pytestを使ったテストの実行（例）
          pytest tests/
      # テストの結果を保存（オプション）
      - name: Save test results
        if: always()  # テストが失敗しても実行する
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/reports/*.xml  # pytestでJUnit形式のレポートを保存している場合

  deploy:
    needs: test  # testジョブが成功した場合に実行
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python for deploy (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Render CLIのインストール
      - name: Install Render CLI
        run: npm install -g render-cli

      # Renderにデプロイ
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # GitHub Secretsに保存したAPIキー
        run: render deploy csthl69u0jms73eknun0?key=MpKAVnbype8

      # デプロイ後の成功通知（任意）
      - name: Notify deployment success
        if: success()
        run: echo "Deployment was successful!"

      # デプロイ後の失敗通知（任意）
      - name: Notify deployment failure
        if: failure()
        run: echo "Deployment failed!"


